color0 #182125
color1 #fd4663
color2 #67d4e4
color3 #5c88d6
color4 #7366cc
color5 #93e0ec
color6 #96b4e9
color7 #f2f3f3
color8 #5b6d6f
color9 #fd4663
color10 #67d4e4
color11 #5c88d6
color12 #7366cc
color13 #93e0ec
color14 #96b4e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #182125
background            #182125
foreground            #f2f3f3
selection_foreground  #afb5b6
selection_background  #212c31
active_border_color   #67d4e4
inactive_border_color #212c31
url_color             #67d4e4
