map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

font_family      JetBrains Mono

font_size 14.0

allow_remote_control yes
listen_on unix:/tmp/kitty


confirm_os_window_close 0

include current-theme.conf

cursor_trail 2






























































































































































































































































































































































































































































































































