#!/usr/bin/env python3
import json
import subprocess
import os
import shutil
import re
from pathlib import Path

# --- Configuration & Paths ---
HOME = Path.home()
CONFIG = HOME / ".config"
CACHE = HOME / ".cache"
STATE_FILE = CACHE / "hypr_performance_state.json"

HYPR_DIR = CONFIG / "hypr"
HYPR_CONF = HYPR_DIR / "hyprland.conf"
PERF_CONF = HYPR_DIR / "performance-mode.conf"
ACTIVE_COLORS = HYPR_DIR / "active-colors.conf"
NOCTALIA_COLORS = HYPR_DIR / "noctalia/noctalia-colors.conf"

WAYBAR_MINI_DIR = CONFIG / "waybar-mini"
MINI_COLORS = WAYBAR_MINI_DIR / "colors-mini.conf"
WAYBAR_CONFIG = WAYBAR_MINI_DIR / "config.jsonc"
WAYBAR_STYLE = WAYBAR_MINI_DIR / "style.css"

KITTY_CONF = CONFIG / "kitty/kitty.conf"
KITTY_MINI_INC = CONFIG / "kitty/waybar-mini.conf" 
KITTY_MINI_SRC = WAYBAR_MINI_DIR / "kitty-mini.conf"

YAZI_THEME = CONFIG / "yazi/theme.toml"

VSCODE_SETTINGS = CONFIG / "Code/User/settings.json"

# --- Helper Functions ---

def run(cmd):
    """Run a command in background to avoid blocking."""
    subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)

def run_sync(cmd):
    """Run a command and wait (only for critical operations)."""
    return subprocess.run(cmd, capture_output=True, text=True)

def kill(process_name):
    subprocess.run(["killall", "-q", process_name])

def update_vscode_theme(theme_name):
    if not VSCODE_SETTINGS.exists(): return
    try:
        with open(VSCODE_SETTINGS, 'r') as f:
            data = json.load(f)
        data["workbench.colorTheme"] = theme_name
        with open(VSCODE_SETTINGS, 'w') as f:
            json.dump(data, f, indent=4)
    except: pass

def ensure_hypr_source():
    if not HYPR_CONF.exists(): return
    content = HYPR_CONF.read_text()
    if "performance-mode.conf" not in content:
        with open(HYPR_CONF, "a") as f:
            f.write(f"\n# Performance Mode Overrides\nsource = {PERF_CONF}\n")

def update_yazi_theme_dynamic():
    if not YAZI_THEME.exists(): return
    colors_file = CONFIG / "noctalia/colors.json"
    icons_tmpl = CONFIG / "yazi/flavors/noctalia.yazi/icons.toml.tmpl"
    
    if not colors_file.exists():
        YAZI_THEME.write_text("[flavor]\ndark = \"noctalia\"\nlight = \"noctalia\"\n")
        return

    try:
        with open(colors_file, 'r') as f:
            c = json.load(f)
        
        flavor_path = CONFIG / "yazi/flavors/noctalia.yazi/flavor.toml"
        if not flavor_path.parent.exists(): flavor_path.parent.mkdir(parents=True)
        
        # Base styles with dynamic colors
        flavor_content = f"""# Generated by performance script
[mgr]
cwd = {{ fg = "{c.get('mOnSurface', '#f3f2f2')}" }}
find_keyword = {{ fg = "{c.get('mError', '#b63936')}", bold = true, italic = true, underline = true }}
find_position = {{ fg = "{c.get('mError', '#b63936')}", bold = true, italic = true }}
marker_copied = {{ fg = "{c.get('mHover', '#ccaa66')}", bg = "{c.get('mHover', '#ccaa66')}" }}
marker_cut = {{ fg = "{c.get('mHover', '#ccaa66')}", bg = "{c.get('mHover', '#ccaa66')}" }}
marker_marked = {{ fg = "{c.get('mError', '#b63936')}", bg = "{c.get('mError', '#b63936')}" }}
marker_selected = {{ fg = "{c.get('mHover', '#ccaa66')}", bg = "{c.get('mHover', '#ccaa66')}" }}
count_copied = {{ fg = "{c.get('mOnSurface', '#f3f2f2')}", bg = "{c.get('mHover', '#ccaa66')}" }}
count_cut = {{ fg = "{c.get('mOnSurface', '#f3f2f2')}", bg = "{c.get('mHover', '#ccaa66')}" }}
count_selected = {{ fg = "{c.get('mOnPrimary', '#25181d')}", bg = "{c.get('mHover', '#ccaa66')}" }}
border_style  = {{ fg = "{c.get('mPrimary', '#e46790')}" }}

[status]
overall = {{ fg = "{c.get('mPrimary', '#e46790')}" }}
sep_left  = {{ open = "", close = "" }}
sep_right = {{ open = "", close = "" }}
progress_label = {{ bold = true }}
progress_normal = {{ fg = "{c.get('mPrimary', '#e46790')}", bg = "{c.get('mSurface', '#29141b')}" }}
progress_error = {{ fg = "{c.get('mError', '#b63936')}", bg = "{c.get('mSurface', '#29141b')}" }}
perm_type = {{ fg = "{c.get('mSecondary', '#d6705c')}" }}
perm_write = {{ fg = "{c.get('mTertiary', '#ccaa66')}" }}
perm_exec = {{ fg = "{c.get('mError', '#b63936')}" }}
perm_read = {{ fg = "{c.get('mHover', '#694e16')}" }}
perm_sep = {{ fg = "{c.get('mPrimary', '#8d0c36')}" }}

[mode]
normal_main = {{ bg = "{c.get('mPrimary', '#e46790')}", fg = "{c.get('mOnPrimary', '#25181d')}", bold = true }}
normal_alt  = {{ bg = "{c.get('mSurfaceVariant', '#371b24')}", fg = "{c.get('mOnSurfaceVariant', '#b6afb1')}" }}
select_main = {{ bg = "{c.get('mSecondary', '#d6705c')}", fg = "{c.get('mOnSecondary', '#25181d')}", bold = true }}
select_alt  = {{ bg = "{c.get('mSurfaceVariant', '#371b24')}", fg = "{c.get('mOnSurfaceVariant', '#b6afb1')}" }}
unset_main = {{ bg = "{c.get('mTertiary', '#ccaa66')}", fg = "{c.get('mOnTertiary', '#25181d')}", bold = true }}
unset_alt  = {{ bg = "{c.get('mSurfaceVariant', '#371b24')}", fg = "{c.get('mOnSurfaceVariant', '#b6afb1')}" }}

[input]
border = {{ fg = "{c.get('mPrimary', '#e46790')}" }}
value = {{ fg = "{c.get('mOnSurface', '#f3f2f2')}" }}
selected = {{ reversed = true }}

[tabs]
active = {{ fg = "{c.get('mPrimary', '#e46790')}", bold = true, bg = "{c.get('mSurface', '#29141b')}" }}
inactive = {{ fg = "{c.get('mSecondary', '#d6705c')}", bg = "{c.get('mSurface', '#29141b')}" }}

[cmp]
border = {{ fg = "{c.get('mPrimary', '#e46790')}", bg = "{c.get('mOnPrimary', '#25181d')}" }}

[tasks]
border = {{ fg = "{c.get('mPrimary', '#e46790')}" }}

[which]
mask = {{ bg = "{c.get('mSurface', '#29141b')}" }}
cand = {{ fg = "{c.get('mPrimary', '#e46790')}" }}
rest = {{ fg = "{c.get('mOnPrimary', '#25181d')}" }}
desc = {{ fg = "{c.get('mOnSurface', '#f3f2f2')}" }}
separator_style = {{ fg = "{c.get('mOnSurface', '#f3f2f2')}" }}

[notify]
title_info = {{ fg = "{c.get('mTertiary', '#ccaa66')}" }}
title_warn = {{ fg = "{c.get('mPrimary', '#e46790')}" }}
title_error = {{ fg = "{c.get('mError', '#b63936')}" }}
"""
        # Append icons and filetypes from template
        if icons_tmpl.exists():
            flavor_content += "\n" + icons_tmpl.read_text()
            
        flavor_path.write_text(flavor_content)
        YAZI_THEME.write_text("[flavor]\ndark = \"noctalia\"\nlight = \"noctalia\"\n")
    except Exception as e:
        print(f"Error updating Yazi theme: {e}")


# --- Mode Switchers ---

def enable_ultra():
    # 1. Hyprland Overrides (Мгновенно)
    ensure_hypr_source()
    PERF_CONF.write_text("""
# AUTOMATICALLY GENERATED BY PERFORMANCE SCRIPT
$blurEnabled = false
$shadowEnabled = false
$windowRounding = 0
$workspaceGaps = 0
$windowGapsIn = 0
$windowGapsOut = 0
$singleWindowGapsOut = 0
$windowBorderSize = 2
$activeWindowBorderColour = rgba(45475aee)
$inactiveWindowBorderColour = rgba(15121bee)

general {
    gaps_in = 0
    gaps_out = 0
    gaps_workspaces = 0
    border_size = 2
    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour
}
decoration {
    rounding = 0
    shadow:enabled = false
    blur:enabled = false
}
animations {
    enabled = false
}
""")
    
    # Смена симлинка цветов
    if ACTIVE_COLORS.is_symlink() or ACTIVE_COLORS.exists():
        ACTIVE_COLORS.unlink()
    if MINI_COLORS.exists():
        ACTIVE_COLORS.symlink_to(MINI_COLORS)

    # Применяем настройки Hyprland ПЕРВЫМИ
    run_sync(["hyprctl", "batch", "reload; notify-send 'Performance' 'ULTRA Mode Enabled' -t 1000"])

    # 2. Остальное в фоне, чтобы не тормозить UI
    # GTK
    run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita-dark"])
    run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", "Adwaita"])
    
    # Kitty
    if KITTY_CONF.exists():
        content = KITTY_CONF.read_text()
        if "include waybar-mini.conf" not in content:
            content += "\ninclude waybar-mini.conf\n"
        content = re.sub(r"background_opacity\s+[\d\.]+", "background_opacity 1.0", content)
        KITTY_CONF.write_text(content)
        if KITTY_MINI_SRC.exists():
            shutil.copy(KITTY_MINI_SRC, KITTY_MINI_INC)
        run(["kitty", "@", "set-colors", "--all", str(KITTY_MINI_SRC)])
        run(["kitty", "@", "set-background-opacity", "--all", "1.0"])

    # VS Code & Fish
    update_vscode_theme("Default Dark Modern")
    run(["fish", "-c", "set -Ux fish_color_scheme Snowman"])

    # Yazi (Set to mini flavor for ULTRA)
    if YAZI_THEME.exists():
        YAZI_THEME.write_text("[flavor]\ndark = \"mini\"\nlight = \"mini\"\n")

    # Shell
    kill("quickshell")
    run(["waybar", "-c", str(WAYBAR_CONFIG), "-s", str(WAYBAR_STYLE)])

def disable_ultra():
    # 1. Hyprland Restores (Мгновенно)
    PERF_CONF.write_text("# Performance Mode Disabled\n")
    if ACTIVE_COLORS.is_symlink() or ACTIVE_COLORS.exists():
        ACTIVE_COLORS.unlink()
    if NOCTALIA_COLORS.exists():
        ACTIVE_COLORS.symlink_to(NOCTALIA_COLORS)

    run_sync(["hyprctl", "batch", "reload; notify-send 'Performance' 'Normal Mode Restored' -t 1000"])

    # 2. Остальное в фоне
    run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "adw-gtk3-dark"])
    run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", "kora-grey"])

    if KITTY_CONF.exists():
        content = KITTY_CONF.read_text()
        content = content.replace("include waybar-mini.conf", "")
        content = re.sub(r"background_opacity\s+[\d\.]+", "background_opacity 0.75", content)
        KITTY_CONF.write_text(content)
        if KITTY_MINI_INC.exists(): KITTY_MINI_INC.unlink()
        run(["kitty", "@", "set-background-opacity", "--all", "0.75"])
        run(["killall", "-USR1", "kitty"])

    update_vscode_theme("Cyberpunk")
    run(["fish", "-c", "set -Ux fish_color_scheme Dracula"])

    # Yazi (Dynamic theme based on Noctalia)
    update_yazi_theme_dynamic()

    kill("waybar")
    run(["quickshell", "-c", "noctalia-shell"])

# --- Main Logic ---

if __name__ == "__main__":
    if not STATE_FILE.exists():
        enable_ultra()
        STATE_FILE.write_text("ultra")
    else:
        disable_ultra()
        if STATE_FILE.exists(): STATE_FILE.unlink()
