#!/usr/bin/env python3
import json
import subprocess
import os
import shutil
import re
from pathlib import Path

# --- Configuration & Paths ---
HOME = Path.home()
CONFIG = HOME / ".config"
CACHE = HOME / ".cache"
STATE_FILE = CACHE / "hypr_performance_state.json"

HYPR_DIR = CONFIG / "hypr"
HYPR_CONF = HYPR_DIR / "hyprland.conf"
PERF_CONF = HYPR_DIR / "performance-mode.conf"
ACTIVE_COLORS = HYPR_DIR / "active-colors.conf"

WAYBAR_MINI_DIR = CONFIG / "waybar-mini"
WAYBAR_CONFIG = WAYBAR_MINI_DIR / "config.jsonc"
WAYBAR_STYLE = WAYBAR_MINI_DIR / "style.css"

KITTY_CONF = CONFIG / "kitty/kitty.conf"
KITTY_MINI_INC = CONFIG / "kitty/waybar-mini.conf" 
KITTY_MINI_SRC = WAYBAR_MINI_DIR / "kitty-mini.conf"

VSCODE_SETTINGS = CONFIG / "Code/User/settings.json"

def run(cmd):
    subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)

def run_sync(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)

def update_vscode_theme(theme_name):
    if not VSCODE_SETTINGS.exists(): return
    try:
        with open(VSCODE_SETTINGS, 'r') as f:
            data = json.load(f)
        data["workbench.colorTheme"] = theme_name
        with open(VSCODE_SETTINGS, 'w') as f:
            json.dump(data, f, indent=4)
    except: pass

def ensure_hypr_source():
    if not HYPR_CONF.exists(): return
    content = HYPR_CONF.read_text()
    if "performance-mode.conf" not in content:
        with open(HYPR_CONF, "a") as f:
            f.write(f"\n# Performance Mode Overrides\nsource = {PERF_CONF}\n")

def enable_ultra():
    ensure_hypr_source()
    PERF_CONF.write_text("""
# AUTOMATICALLY GENERATED BY PERFORMANCE SCRIPT
$blurEnabled = false
$shadowEnabled = false
$windowRounding = 0
$workspaceGaps = 0
$windowGapsIn = 0
$windowGapsOut = 0
$windowBorderSize = 2

general {
    gaps_in = 0
    gaps_out = 0
    gaps_workspaces = 0
    border_size = 2
}
decoration {
    rounding = 0
    shadow:enabled = false
    blur:enabled = false
}
animations {
    enabled = false
}
""")
    
    run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita-dark"])
    run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", "Adwaita"])
    
    if KITTY_CONF.exists():
        content = KITTY_CONF.read_text()
        if "include waybar-mini.conf" not in content:
            content += "\ninclude waybar-mini.conf\n"
        content = re.sub(r"background_opacity\s+[\d\.]+", "background_opacity 1.0", content)
        KITTY_CONF.write_text(content)
        if KITTY_MINI_SRC.exists(): shutil.copy(KITTY_MINI_SRC, KITTY_MINI_INC)
        run(["kitty", "@", "set-background-opacity", "--all", "1.0"])

    update_vscode_theme("Default Dark Modern")
    run(["fish", "-c", "set -Ux fish_color_scheme Snowman"])

    run_sync(["/home/linuxoed/Документы/scripts/kill_shell.sh"])
    run(["waybar", "-c", str(WAYBAR_CONFIG), "-s", str(WAYBAR_STYLE)])
    run_sync(["hyprctl", "batch", "reload; notify-send 'Performance' 'ULTRA Mode Enabled' -t 1000"])

def disable_ultra():
    PERF_CONF.write_text("# Performance Mode Disabled\n")
    
    run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "adw-gtk3-dark"])
    run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", "kora-grey"])

    if KITTY_CONF.exists():
        content = KITTY_CONF.read_text()
        content = content.replace("include waybar-mini.conf", "")
        content = re.sub(r"background_opacity\s+[\d\.]+", "background_opacity 0.75", content)
        KITTY_CONF.write_text(content)
        if KITTY_MINI_INC.exists(): KITTY_MINI_INC.unlink()
        run(["kitty", "@", "set-background-opacity", "--all", "0.75"])

    update_vscode_theme("Cyberpunk")
    run(["fish", "-c", "set -Ux fish_color_scheme Dracula"])

    run_sync(["killall", "waybar"])
    run(["/home/linuxoed/Документы/scripts/restart_shell.sh"])
    run_sync(["hyprctl", "batch", "reload; notify-send 'Performance' 'Normal Mode Restored' -t 1000"])

if __name__ == "__main__":
    if not STATE_FILE.exists():
        enable_ultra()
        STATE_FILE.write_text("ultra")
    else:
        disable_ultra()
        if STATE_FILE.exists(): STATE_FILE.unlink()
